#!/bin/sh

chromium_players="$(playerctl -l | grep chromium | xargs | sed 's/ /,/g')"

if test "$(playerctl -i "$chromium_players" status)" = "Playing"; then
	echo -n $(playerctl -i "$chromium_players" metadata title)
	echo -n ' - '
	echo -n $(playerctl -i "$chromium_players" metadata artist)
fi
